version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ferment-postgres
    environment:
      POSTGRES_USER: ferment
      POSTGRES_PASSWORD: ferment
      POSTGRES_DB: ferment_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
